name: Docker Image CI

on:
  push:
    branches: [ main ] # Здесь указывается название ветки, которую нужно выкатывать
  workflow_dispatch:
jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Это переменная с логином к Docker 
        password: ${{ secrets.DOCKER_PASSWORD }} # Это переменная с паролем к Docker
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: immoltex/my_python_app:latest

  deploy:
      name: Deploy the app
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub
      steps:
      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop main_container 
            sudo docker system prune -a -f
            sudo docker pull immoltex/my_python_app:latest 
            sudo nohup docker run --name main_container -d
